# Prometheus設定
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ServiceGrid バックエンド監視
  - job_name: 'servicegrid-backend'
    static_configs:
      - targets: ['backend:8082']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # ServiceGrid フロントエンド監視
  - job_name: 'servicegrid-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node Exporter (システムメトリクス)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']