#!/bin/bash

# 手動でペインレイアウトを調整するための案内スクリプト

echo "🔧 tmuxペイン手動レイアウト調整ガイド"
echo ""
echo "目標レイアウト:"
echo "┌─────────────────────────────────────┐"
echo "│ 1段目: Feature-B │ Feature-C       │"
echo "│      (UI/テスト)  │ (API開発)       │"
echo "├─────────────────────────────────────┤"
echo "│ 2段目: Feature-D │ Feature-E       │"
echo "│   (PowerShell)   │ (非機能要件)    │"
echo "├─────────────────────────────────────┤"
echo "│ 3段目: Feature-A (統合リーダー)     │"
echo "│              全幅                   │"
echo "└─────────────────────────────────────┘"
echo ""
echo "📋 tmux内での手動調整手順:"
echo ""
echo "1. 🎯 Feature-A（統合リーダー）を最下段に配置:"
echo "   Ctrl+b + 1    # Feature-Aペインを選択"
echo "   Ctrl+b + }    # ペインを下に移動（複数回実行）"
echo ""
echo "2. 🎨 Feature-B（UI/テスト）を左上に配置:"
echo "   Ctrl+b + 2    # Feature-Bペインを選択"
echo "   Ctrl+b + {    # ペインを上に移動（必要に応じて）"
echo ""
echo "3. 🔧 Feature-C（API開発）を右上に配置:"
echo "   Ctrl+b + 3    # Feature-Cペインを選択"
echo "   Ctrl+b + o    # ペイン移動"
echo ""
echo "4. レイアウト調整:"
echo "   Ctrl+b + Alt+1   # even-horizontal レイアウト"
echo "   Ctrl+b + Alt+2   # even-vertical レイアウト"
echo "   Ctrl+b + Alt+3   # main-horizontal レイアウト"
echo "   Ctrl+b + Alt+4   # main-vertical レイアウト"
echo "   Ctrl+b + Alt+5   # tiled レイアウト"
echo ""
echo "5. ペインサイズ調整:"
echo "   Ctrl+b + H/J/K/L  # ペインサイズ変更（5文字ずつ）"
echo "   Ctrl+b + 矢印     # ペインサイズ微調整"
echo ""
echo "⭐ 推奨手順:"
echo "1. main-horizontal レイアウトを選択"
echo "2. Feature-A を main-pane（下段）に設定"
echo "3. 上段4ペインを even-horizontal で調整"
echo ""
echo "🔧 自動調整を試す場合:"
echo "   ./rearrange-panes.sh"
echo ""
echo "💡 現在のペイン配置確認:"
echo "   Ctrl+b + q       # ペイン番号を表示"